In [2]:
import numpy as np
import time

# 1. CREATE AND MANIPULATE 1D, 2D AND 3D NUMPY ARRAYS


print("========== 1D ARRAY ==========")

arr_1d = np.array([10, 20, 30, 40, 50])

print("1D Array:", arr_1d)
print("Shape:", arr_1d.shape)

# Manipulation
print("First element:", arr_1d[0])
print("Last element:", arr_1d[-1])

arr_1d = arr_1d * 2
print("After multiplying by 2:", arr_1d)


print("\n========== 2D ARRAY ==========")

arr_2d = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("2D Array:")
print(arr_2d)

print("Shape:", arr_2d.shape)
print("First row:", arr_2d[0])
print("First column:", arr_2d[:, 0])

# Change value
arr_2d[0, 0] = 100
print("After changing first value:")
print(arr_2d)


print("\n========== 3D ARRAY ==========")

arr_3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print("3D Array:")
print(arr_3d)

print("Shape:", arr_3d.shape)
print("Number of dimensions:", arr_3d.ndim)



# 2. VECTORIZED OPERATIONS


print("\n========== VECTORIZED OPERATIONS ==========")

a = np.array([10, 20, 30, 40, 50])
b = np.array([1, 2, 3, 4, 5])

print("Array A:", a)
print("Array B:", b)

# Addition
print("Addition:", a + b)

# Multiplication
print("Multiplication:", a * b)

# Subtraction
print("Subtraction:", a - b)

# Division
print("Division:", a / b)



# AGGREGATE OPERATIONS ACROSS AXES


matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("\nMatrix:")
print(matrix)

print("Total:", np.sum(matrix))
print("Mean:", np.mean(matrix))

# Axis 0 = column-wise
print("Sum across axis 0:", np.sum(matrix, axis=0))

# Axis 1 = row-wise
print("Sum across axis 1:", np.sum(matrix, axis=1))



# 3. BOOLEAN MASKING AND FANCY INDEXING


print("\n========== BOOLEAN MASKING ==========")

numbers = np.array([10, 25, 40, 55, 70, 85, 100])

print("Original:", numbers)

# Select numbers greater than 50
mask = numbers > 50

print("Boolean mask:", mask)
print("Numbers greater than 50:", numbers[mask])

# Select numbers between 30 and 80
selected = numbers[(numbers >= 30) & (numbers <= 80)]

print("Numbers between 30 and 80:", selected)


print("\n========== FANCY INDEXING ==========")

numbers = np.array([10, 20, 30, 40, 50, 60])

indexes = [0, 2, 5]

print("Original:", numbers)
print("Selected indexes:", indexes)
print("Selected values:", numbers[indexes])



# 4. STATISTICAL MEASURES


print("\n========== STATISTICAL MEASURES ==========")

data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print("Data:", data)

# Mean
print("Mean:", np.mean(data))

# Standard deviation
print("Standard Deviation:", np.std(data))

# Percentile
print("50th Percentile:", np.percentile(data, 50))
print("90th Percentile:", np.percentile(data, 90))

# Minimum and Maximum
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))


# =========================================================
# CORRELATION
# =========================================================

print("\n========== CORRELATION ==========")

hours_studied = np.array([1, 2, 3, 4, 5, 6])
marks = np.array([40, 45, 55, 60, 70, 80])

correlation_matrix = np.corrcoef(hours_studied, marks)

print("Hours studied:", hours_studied)
print("Marks:", marks)

print("Correlation matrix:")
print(correlation_matrix)

print("Correlation coefficient:",
      correlation_matrix[0, 1])


# =========================================================
# 5. NUMPY PERFORMANCE VS PYTHON LOOP
# =========================================================

print("\n========== PERFORMANCE COMPARISON ==========")

# Create 1 million numbers
data = np.arange(1_000_000)


# Python loop


start_time = time.time()

loop_result = []

for number in data:
    loop_result.append(number * 2)

loop_time = time.time() - start_time



# NumPy vectorization


start_time = time.time()

numpy_result = data * 2

numpy_time = time.time() - start_time


print("Dataset size:", len(data))

print("Python loop time:",
      loop_time, "seconds")

print("NumPy vectorized time:",
      numpy_time, "seconds")


if numpy_time > 0:
    print("NumPy speed improvement:",
          loop_time / numpy_time,
          "times faster")



# FINAL MESSAGE



========== 1D ARRAY ==========
1D Array: [10 20 30 40 50]
Shape: (5,)
First element: 10
Last element: 50
After multiplying by 2: [ 20  40  60  80 100]

========== 2D ARRAY ==========
2D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Shape: (3, 3)
First row: [10 20 30]
First column: [10 40 70]
After changing first value:
[[100  20  30]
 [ 40  50  60]
 [ 70  80  90]]

========== 3D ARRAY ==========
3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)
Number of dimensions: 3

========== VECTORIZED OPERATIONS ==========
Array A: [10 20 30 40 50]
Array B: [1 2 3 4 5]
Addition: [11 22 33 44 55]
Multiplication: [ 10  40  90 160 250]
Subtraction: [ 9 18 27 36 45]
Division: [10. 10. 10. 10. 10.]

Matrix:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Total: 450
Mean: 50.0
Sum across axis 0: [120 150 180]
Sum across axis 1: [ 60 150 240]

========== BOOLEAN MASKING ==========
Original: [ 10  25  40  55  70  85 100]
Boolean mask: [False False False  True  True  True  True]
Number